### ISSUE TITLE
how to use websocket with  desmos-connect

### ISSUE THREAD

**Issue by gigabyteservice** [cameronthecoder/desmos-connect#2]
Feature recommendation: creating collaborative desmos using own WebSocket server

**Comment by cameronthecoder** [comment]
Hi! Thanks for the suggestion, but I am a little confused. Are you asking how to use Desmos with a WebSocket server or are you suggesting that I use a WebSocket server to send data between clients in the Adobe Connect room? To use a WebSocket server with the Desmos API, you can use the `calculator.getState()` and the `calculator.observeEvent("change", onCalculatorStateChanged);` to observe when the calculator's state has changed. See [this page.](https://www.desmos.com/api/v1.7/docs/index.html#GraphingCalculator-change-event) If it's the ladder, why not use the SDK that Adobe Connect provides? It seems to work fine but I am open to other suggestions :)

**Comment by gigabyteservice** [comment]
suggesting to use Desmos with a custom ( your own like socket.io or  https://github.com/uNetworking/uWebSockets.js which is [8.5x that of Fastify](https://alexhultman.medium.com/serving-100k-requests-second-from-a-fanless-raspberry-pi-4-over-ethernet-fdd2c2e05a1e) and at least [10x that of Socket.IO](https://medium.com/swlh/100k-secure-websockets-with-raspberry-pi-4-1ba5d2127a23).) Websocket server so people don't need to depend on Adobe Connect w e.g if uer1 joins example.com/room/xyz and user2 will join example.com/room/xyz  both can collaborate and interact with each other on Desmos & user3 join example.com/room/abc. and user4 on example.com/room/abc so user3 and user4 can work together without interfering user1 & user2.

**Comment by cameronthecoder** [comment]
I see what you're saying, but the purpose of this project is to integrate specifically with Adobe Connect. For this reason, I am unfortunately going to have to close this issue. Thank you for the suggestion though.
